const technologies = [
  {
    id: 1,
    name: "React",
    category: "Frontend",
    description: "A declarative, component-based JavaScript library for building modern user interfaces.",
    level: "Beginner-Friendly",
    rating: "4.9",
    badge: "Popular",
    badgeClass: "popular",
    logo:  "https://raw.githubusercontent.com/devicons/devicon/master/icons/react/react-original.svg",
  },
  {
    id: 2,
    name: "Vue.js",
    category: "Frontend",
    description: "An approachable, performant, and versatile framework for building web user interfaces.",
    level: "Beginner-Friendly",
    rating: "4.8",
    badge: "Versatile",
    badgeClass: "versatile",
    logo:  "https://raw.githubusercontent.com/devicons/devicon/master/icons/vuejs/vuejs-original.svg",
  },
  {
    id: 3,
    name: "Svelte",
    category: "Frontend",
    description: "Cybernetically enhanced web apps with compile-time reactivity and zero virtual DOM overhead.",
    level: "Beginner-Friendly",
    rating: "4.8",
    badge: "Fast",
    badgeClass: "fast",
    logo: "https://raw.githubusercontent.com/devicons/devicon/master/icons/svelte/svelte-original.svg",
  },
  {
    id: 4,
    name: "Next.js",
    category: "Frontend",
    description: "The React framework for full-stack web applications with hybrid static & server rendering.",
    level: "Intermediate",
    rating: "4.9",
    badge: "",
    badgeClass: "",
    logo: "https://raw.githubusercontent.com/devicons/devicon/master/icons/nextjs/nextjs-original.svg",
  },
  {
    id: 5,
    name: "Node.js",
    category: "Backend",
    description: "An asynchronous event-driven JavaScript runtime built on Chrome's V8 engine.",
    level: "Beginner-Friendly",
    rating: "4.8",
    badge: "Standard",
    badgeClass: "standard",
    logo: "https://raw.githubusercontent.com/devicons/devicon/master/icons/nodejs/nodejs-original.svg",
  },
  {
    id: 6,
    name: "PostgreSQL",
    category: "Database",
    description: "A powerful, open-source object-relational database system with proven reliability.",
    level: "Intermediate",
    rating: "4.9",
    badge: "Top SQL",
    badgeClass: "top-sql",
    logo:"https://raw.githubusercontent.com/devicons/devicon/master/icons/postgresql/postgresql-original.svg",
  },
  {
    id: 7,
    name: "Redis",
    category: "Database",
    description: "In-memory data structure store used as a high-speed database, cache, and message broker.",
    level: "Intermediate",
    rating: "4.8",
    badge: "Cache",
    badgeClass: "cache",
    logo: "https://raw.githubusercontent.com/devicons/devicon/master/icons/redis/redis-original.svg",
  },
  {
    id: 8,
    name: "JavaScript",
    category: "Language",
    description: "The versatile, ubiquitous scripting language powering dynamic behavior across the web.",
    level: "Beginner-Friendly",
    rating: "4.9",
    badge: "Ubiquitous",
    badgeClass: "ubiquitous",
    logo: "https://raw.githubusercontent.com/devicons/devicon/master/icons/javascript/javascript-original.svg", 
  },
  {
    id: 9,
    name: "TypeScript",
    category: "Language",
    description: "A strongly typed programming language that builds on JavaScript for robust tooling.",
    level: "Intermediate",
    rating: "4.9",
    badge: "Essential",
    badgeClass: "essential",
    logo:"https://raw.githubusercontent.com/devicons/devicon/master/icons/typescript/typescript-original.svg",
  },
  {
    id: 10,
    name: "Java",
    category: "Language",
    description: "A secure, object-oriented programming language designed for portability and scale.",
    level: "Intermediate",
    rating: "4.6",
    badge: "Robust",
    badgeClass: "robust",
    logo: "https://raw.githubusercontent.com/devicons/devicon/master/icons/java/java-original.svg",
  },
  {
    id: 11, 
    name: "Tailwind CSS",
    category: "Styling",
    description: "A utility-first CSS framework packed with classes that can be composed to build custom UI.",
    level: "Beginner-Friendly",
    rating: "4.9",
    badge: "Modern",
    badgeClass: "modern",
    logo: "https://raw.githubusercontent.com/devicons/devicon/master/icons/tailwindcss/tailwindcss-original.svg",
  
  },
  {
    id: 12,
    name: "Docker",
    category: "DevOps",
    description: "A platform designed to build, share, and run containerized applications reliably.",
    level: "Intermediate",
    rating: "4.9",
    badge: "Containers",
    badgeClass: "containers",
    logo: "https://raw.githubusercontent.com/devicons/devicon/master/icons/docker/docker-original.svg",
  },
];

export default technologies;